### ISSUE TITLE
SQL database dump

### ISSUE THREAD

**Issue by rubennaatje** [gdsotirov/lemans24#1]
Any way possible you can add a sql db dump to this @gdsotirov?

**Comment by gdsotirov** [comment]
> Any way possible you can add a sql db dump to this @gdsotirov?

@rubennaatje You mean with loaded data?

**Comment by rubennaatje** [comment]
Yes exactly, just a single sql script to create the whole database. I think you can easily generate that file from mysql workbench. 

This seems like an amazing db.

**Comment by gdsotirov** [comment]
Thanks. You are right that one could easily generate database creation script from MySQL Workbench, but this won't include data. In fact, the (undocumented) procedure to create the database with all the data is:

- First, create database structure with MySQL Workbench using file `db/model/lemans24.mwb` and _Synchronize Model..._ from _Database_ menu;
- Then, import data (these are `*.csv` files from `db/data/` directory) with _Table Data Import Wizard_ in MySQL Workbench + execute file `db/data/tyres.sql`;
- Finally, execute procedure `process_results` (e.g. with `call process_results()`).

Having written it however, I now understand that it may be OK for me, but I must provide an easier way for everyone else to use the project, which includes creating database and loading data. So, thanks for reporting the issue. I would think how to organize it and would hopefully have a solution for you soon.

**Comment by rubennaatje** [comment]
Thanks a lot @gdsotirov for looking into it.

**Comment by gdsotirov** [comment]
Notes to self:
- Date is more often updated than database structure, so perhaps two separate dumps for structure and data would be more suitable;
- Having structure as single file and separate file per database object (e.g. tables, views, routines, etc.) would mean the structure dump would have to be synchronized together with changes to these objects and contradicts [DRY principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself);
- Window functions used in views `Races` and `Winners` require MySQL 8.0.2 or later, while everything else would also work on MySQL 5.7.6 or newer;
- MySQL Workbench always generates indexes with `VISIBLE` keyword no mater target server's version (see [bug 95804](https://bugs.mysql.com/bug.php?id=95804));
- There are some slight differences between model and database on server:
  * foreign keys [referential actions](https://dev.mysql.com/doc/refman/8.0/en/create-table-foreign-keys.html#foreign-key-referential-actions) (`ON DELETE` should be `RESTRICT`, but it's either missing or `NO ACTION`);
  * columns `results.racing_time` and `results_in.racing_time` sizes (see [bug 81123](https://bugs.mysql.com/bug.php?id=81123)).
- Data is currently spread in `*.csv` files and a SQL script;
- Need to update README with the procedure defined in my previous comment to have it documented.

**Comment by gdsotirov** [comment]
@rubennaatje There is now the option to create schema and import data with pre-generated SQL scripts as described in the README. I have chosen to split structure from data, because data is more frequently updated than structure, so it would be easy to just re-import the data dump. Please, try the scripts and let me know if you encounter any issues.

**Comment by rubennaatje** [comment]
@gdsotirov Amazing, thanks works very well! :)
